# Generated by Django 5.2.4 on 2025-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_num', models.BigAutoField(default='12345678900', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('gender', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('aadhar', models.PositiveBigIntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=7)),
                ('pin', models.CharField(null=True)),
            ],
        ),
    ]
